"use strict";


module.exports = {
	EXPRESS_PORT: 3000,

	// TWITTER
	TWITTER_CONSUMER_KEY: '...',
	TWITTER_CONSUMER_SECRET: '...',
	TWITTER_ACCESS_TOKEN_KEY: '...',
	TWITTER_ACCESS_TOKEN_SECRET: '...'
}